### ISSUE TITLE
Callback when modifying collections with namedContext (SimpleSchema) does not work (collection2)

### ISSUE THREAD

**Issue by raphaelarias** [cult-of-coders/redis-oplog#156] opened 2017-05-31 13:31 UTC
Hi.

Congratulations for the great work. Just a quick question.

We have several methods that after an insert it does something. A saw that, after i started using redis-oplog these callbacks were not firing at all.

And when a seletor was being used to select the proper schema for validation, we got the error:
Not possible to read namedContext of null.

Would you know if we are doing something wrong?

We have the optimistic set to true in the settings.json

Thank you very much!

**Comment by theodorDiaconu** [comment] 2017-06-09 10:17
@raphaelarias we have support and tests for collection hooks. CAn you try adding redis-oplog before or after collection-hooks, see how that works on ? Thank you!

**Comment by raphaelarias** [comment] 2017-06-11 18:19
I'm very sorry, apprently it is working now.

We do use collection hooks, but the "problem" was when doing a mongo operation in a method. The callback wasn't firing, this is for sure.

I had 99.9999% it wasn't your package, but it started to happen after we installed and fixed when we removed.

Now we are using Meteor 1.5 and everything works just the way it should be.

I'm sorry again for the inconvenience.

**Comment by raphaelarias** [comment] 2017-06-11 18:58
Ok, So I tested it again, and I found the issue.

In a couple of our collections we are using a named context when attaching the schema (SimpleSchema).

When that's the case every insert or update opertation you have to add a selector:

Collection.insert(data, { selector: { name: 'test' } }, (error) => {
console.log(error);
});

When that's the case, it does not work.

**Comment by raphaelarias** [comment] 2017-06-11 19:45
So, after a few tests, i finily realised that it only occurs in collections where you attach a schema using a named context.

To help, we have a repo:

https://github.com/raphaelarias/redis-oplog-collection2-issue

**Comment by raphaelarias** [comment] 2017-06-21 05:37
Is there anything I can do to help you? I tried to fix myself so I could do a pull request, but I don't have enough knowledge of the codebase, I guess.

**Comment by theodorDiaconu** [comment] 2017-06-21 06:07
@raphaelarias the problem is on .insert(), is that we override the insert method, and we don't further send the other params. 

This is a hard problem, having to play with overriding inserts and stuff, because some people send another params, other don't, and the 2nd param is a callback (by default in meteor) which means there is extra logic that you need to handle. 

Solution would be to allow a config variable, that says: passInsertOptions: true, and inside here:
https://github.com/cult-of-coders/redis-oplog/blob/master/lib/mongo/Mutator.js#L25

Check if that passInsertOptions is true and send that _config to that original insert.

**Comment by raphaelarias** [comment] 2017-06-21 06:12
What if we test if the second parameter that it's usually the callback it's not a function. If it's true we send it to the original insert function.

To make sure nothing will stop working we make this behaviour occur only if it's in the settings, kind of like you said "passInsertOptions".

What do you think? With this solution people who are using packages that have this behaviour can still use the package with no problems.

Am I missing something?

We can do that with x number of arguments, if the last one is a callback (function) it's all fine.

**Comment by theodorDiaconu** [comment] 2017-06-21 06:19
@raphaelarias I think I got it.

Look here: 

https://github.com/cult-of-coders/redis-oplog/blob/master/lib/mongo/Mutator.js#L14
The problem is that now we have collection2-core... not collection2. But we should do both detection of "common" packages, and also allow that option in config.

**Comment by theodorDiaconu** [comment] 2017-06-21 06:29
Actually the passConfigDown was never used, meaning it was useless. I am now thinking of a solution to put an end to this. And solve it 4ever.

**Comment by raphaelarias** [comment] 2017-06-21 06:37
Ok, I understand. Make sense.

So, as far as I know collection-2 is basically the most common package used that modify and expect a second parameter, but may exist others. What if it automatically always pass all the arguments to the original insert function?

As far as I understood the problem occur when _config:

static insert(Originals, data, _config) {

is not a function, so we have to validate if it's is. If true we just call it, otherwise we go through the arguments passing down until we find a function (callback).

Make sense?

As far as I can think, we wouldn't need a special config for that, because it would be backwards compatible.

**Comment by raphaelarias** [comment] 2017-06-21 06:38
You are already validating if it's a function:

if (_.isFunction(_config)) {
                _config.call(this, null, docId);
            }

We can then, do that in the else of this if.

**Comment by theodorDiaconu** [comment] 2017-06-21 06:47
This is how they do it: https://github.com/aldeed/meteor-collection2-core/blob/master/package/collection2/collection2.js#L168

**Comment by raphaelarias** [comment] 2017-06-21 07:10
I'll take a look and try to come up with something too.

**Comment by raphaelarias** [comment] 2017-07-26 12:24
I've opened a new Pull Request. No test is failing, my not sure if is the best way to do it thought. It works.

Do you have a plan to merge fixes and release a new version of the package?

**Comment by theodorDiaconu** [comment] 2017-11-01 12:03
@raphaelarias would this still fail if you load cultofcoders before ?

**Comment by theodorDiaconu** [comment] 2017-11-03 08:35
I think this should be fixed if you just put redis-oplog as the top package.

**Closed by theodorDiaconu** 2017-11-03 08:35 UTC
Labels: need-more-info

**Comment by raphaelarias** [comment] 2017-11-03 12:02
That's nice, an unexpected solution (at least for me) this one.

Congratulations!
