### ISSUE TITLE
[Feature Request $200 Bounty] Make client side mutations propagate to custom channels or namespaces

### ISSUE THREAD

**Issue by copleykj** [cult-of-coders/redis-oplog#207] opened 2017-11-13 16:07 UTC
Currently client side mutations do not get propagated to custom channels or namespaces. I'd love to see this functionality in redis-oplog, so if anyone can accomplish this then the bounty is theirs.

As far as Bounty goes, it's contingent on a complete working and secure solution. Payment can be through paypal, or just about any crypto asset of your choosing (besides Bitcoin due to the current network congestion and ridiculous fees required to get a transaction through).

**Comment by theodorDiaconu** [comment] 2017-11-13 16:13
@copleykj I'm going to take on your offer and begin this. 

API:

```js
Collection.insert(selector, options);
Collection.update(selector, modifier, options);
Collection.remove(selector, options);
```

Only allow `namespace`, `namespaces`, `pushToRedis` and not channels for security.

**Comment by theodorDiaconu** [comment] 2017-11-14 16:57
There is code in aldeed:collection2-core, that doesn't allow me to pass-in options:
https://github.com/aldeed/meteor-collection2-core/blob/master/package/collection2/collection2.js#L205

I managed to pass options and make them hit the server. But now I don't know what to do regarding compatibility with this package with `insert` mutation

If redis-oplog is loaded AFTER aldeed:collection2-core, then it won't work because collection2 strips options out before sending them to the server. If redis-oplog is loaded BEFORE aldeed:collection2-core, then mutation methods get overridden and "options" won't reach our own extensions.

As an alternative I tried embedding the options object inside the document for inserting (as a __options special field). We get into bigger issues.

**Comment by theodorDiaconu** [comment] 2017-11-14 17:04
I added a weak dependency:
```
    api.use('aldeed:collection2-core', {weak: true});
```

And now information gets passed, but I override collection2's core for client-side validation and I also override some possible hooks from collection hooks package.

I had to override the whole insert() prototype to allow me to send options.

**Comment by copleykj** [comment] 2017-11-14 17:08
So this means that this will not work with Collection2-core if it's part of the project or client side collection2 validation for collection2 won't performed till the server?

**Comment by theodorDiaconu** [comment] 2017-11-14 17:11
Yes... mongo mutators aren't very hackable:
https://github.com/cult-of-coders/redis-oplog/pull/208/files

I needed to hook in that part ._callMutatorMethod().

I wouldn't lose hope yet, usually ideas come in time, maybe there is a way.

**Comment by copleykj** [comment] 2017-11-14 17:32
I don't think it should be unreasonable for collection2 to pass on any additional arguments. What do you think of an issue or pull request that fixes this on the collection2-core repo?

**Comment by copleykj** [comment] 2017-11-14 23:33
I've got this working with a very minor modification to collection2-core and the new changes in the `feature/client-side-redis-options` branch. Unfortunately after studying the code for a bit to make the change I realized that it's probably not a change that would be accepted into collection2 since it assumes to be calling the standard `Collection.insert` and would have to provide a special case for when redis-oplog was in use.

**Comment by theodorDiaconu** [comment] 2017-11-15 06:31
@copleykj yup, modifyng collection2 can work in the following manner (and be accepted by aldeed), we need to create a configuration for it:

Example:
```Collection2.passOptionsFurtherFromClient = true```, and it defaults to false.

And RedisOplog can check for existence of this package and apply this change automatically!

And in the override section if that option is true, we simply push "options" to args.

**Comment by theodorDiaconu** [comment] 2017-11-16 13:25
@copleykj I'm waiting for @aldeed to confirm to me that he would accept this in his repo and I can create a PR for it. I believe that's the way to go. But the problem is that we may encounter more issues like this with other packages... so by using your socialize packages some people may experience strange behavior. 

Would it be that much work for you to shift to optimistic methods ? I know you don't want this because, as I do, you enjoy the simplicity that isomorphic mutations offer us. But people move away from this for a good reason, and maybe by splitting them into methods, you can allow the users of your package more flexibility.

**Comment by copleykj** [comment] 2017-11-16 14:34
Unfortunately this would be quite a bit of work at a point when I have very little spare time. In the future If there were issues I would consider it. As far as I can tell though, there should only be a very small chance of this type of conflict with other packages, but only with ones who's functionality is already present in the currently implemented packages.

**Comment by theodorDiaconu** [comment] 2017-11-17 09:31
@copleykj I strongly believe that for your use-case we could use this:
https://github.com/cult-of-coders/redis-oplog/issues/212 

What do you think? Would it treat your needs ? I believe it's more elegant and secure.

**Comment by theodorDiaconu** [comment] 2017-11-17 12:30
@copleykj take a look: https://github.com/cult-of-coders/redis-oplog/blob/master/docs/finetuning.md#configuration-at-collection-level it's published.

**Comment by copleykj** [comment] 2017-11-17 13:03
This looks promising. I'll see about starting implementation today and see how it goes.

**Comment by theodorDiaconu** [comment] 2017-11-17 13:59
@copleykj I think this is also a better suited approach since you offer re-usable packages. It's smarter to work with this approach as you wouldn't want the users to tie themselves with RedisOplog, they may be small users that do not want the hassle of maintaining another redis server. So I think it's the best of both worlds:

- No longer give namespacing rights to clients
- No longer having the need to modify the core mutation methods of Mongo.Collection
- No longer having to modify other packages to make this work
- Your packages can work without redis-oplog
```js
if (Collection.configureRedisOplog) { ... }
```

**Comment by copleykj** [comment] 2017-11-17 14:14
I agree that this is a better approach for namespace rights, and not modifying core and third party functionality. Awesomely though redis-oplog was completely optional even with the previous approach since channel/namespace options were ignored by mutations and cursors. The only place that I had a minor issue was with SyntheticMutator in the messaging package for typing status. In that case I just used require within a try catch and provided a fallback to mongo mutations if it wasn't present.

**Comment by theodorDiaconu** [comment] 2017-11-17 14:30
@copleykj you could also use if (Package['cultofcoders:redis-oplog']) 

Really excited about your packages I think you will be the first to actually solve scalable chat inside Meteor.

**Comment by theodorDiaconu** [comment] 2017-11-17 14:36
I'm closing this issue because it's hard to implement and has too many implications and isomorphic mutations are not recommended anymore. Hopefully the `configureRedisOplog` can help solve the issues.

**Closed by theodorDiaconu** 2017-11-17 14:36 UTC
Labels: enhancement
