### ISSUE TITLE
Meteor.Publish is not working

### ISSUE THREAD

**Issue by srinag63** [cult-of-coders/redis-oplog#120] opened 2017-01-24 05:51 UTC
When im trying to do pub sub using **Meteor.publish** with **"overridePublishFunction": false**, In the server i'm getting Exception from task: TypeError: Cannot read property 'selector' of undefined attached is the error in client
![screenshot from 2017-01-24 11-16-44](https://cloud.githubusercontent.com/assets/3824505/22235721/447c1966-e227-11e6-84c3-31e84c2be7f0.png)

**Comment by theodorDiaconu** [comment] 2017-01-25 13:14
@srinag63 thanks, will investigate.

**Comment by theodorDiaconu** [comment] 2017-01-25 13:48
Duplicate of #108

**Closed by theodorDiaconu** 2017-01-25 13:48 UTC
Labels: bug
