### ISSUE TITLE
Reactivity lost when using Meteor.call() to change document

### ISSUE THREAD

**Issue by nadeemja** [cult-of-coders/redis-oplog#119] opened 2017-01-20 17:07 UTC

**Comment by theodorDiaconu** [comment] 2017-01-23 07:42
@nadeemja pls tell us how does your call look like, and how your publication looks like.

**Comment by nadeemja** [comment] 2017-01-23 22:31
__Method__
```javascript
    const _this = this;

    Meteor.methods({
      likeDocument(collectionName, documentId) {
        check(collectionName, String);
        check(documentId, String);

        const Collection = _this[collectionName];

        const document = Collection.findOne({ _id: documentId });

        if (!document) {
          return false;
        }

        const userAlreadyLiked = _.contains(document.likedBy, Meteor.userId());

        if (userAlreadyLiked) {
          Collection.update({
            _id: documentId,
          }, {
            $pull: {
              likedBy: Meteor.userId(),
            },
          });
        } else {
          Collection.update({
            _id: documentId,
          }, {
            $addToSet: {
              likedBy: Meteor.userId(),
            },
          });
        }

        return !userAlreadyLiked ? 'Liked' : 'Not liked';
      },
    });
```


```javascript
Template.likesButton.events({

  'click #likesButton': function (event, templateInstance) {
    event.preventDefault();

    const collectionName = templateInstance.data.collectionName;

    const documentId = templateInstance.data.doc._id;

    Meteor.call('likeDocument', collectionName, documentId, (error) => {
      if (error) {
        console.log('error', error);
      }
    });
  },

});
```

```javascript

    Meteor.publishComposite('studentQuestionsForSchedule', function pubStudentQuestionsForSchedule(scheduleId) {
      check(scheduleId, String);

      if (!this.userId) {
        return this.ready();
      }

      const user = Users.findOne({ _id: this.userId });

      if (!user) {
        return this.ready();
      }
      const query = {
        schedule_id: scheduleId,
        userType: 'student',
      };
      if (!user.isLecturer(scheduleId)) {
        query.$or = [{
          visibleToOthers: {
            $ne: false,
          },
        }, {
          user_id: this.userId,
        }];
      }

      return {
        find() {
          return Questions.find(query);
        },
        children: [{
          find(question) {
            return Users.find(question.user_id);
          },
        }],
      };
    });
````

**Comment by theodorDiaconu** [comment] 2017-01-25 13:14
@nadeemja thank you, will investigate.

**Comment by theodorDiaconu** [comment] 2017-01-25 17:07
@nadeemja is your method optimistic ? do you execute it on client as well ?

**Comment by nadeemja** [comment] 2017-01-25 17:43
No, but I'll try with optimistic ui too :)

**Comment by theodorDiaconu** [comment] 2017-01-26 06:30
The issue is with publishComposite, I am now writing tests, because multiple people have the same problems.

**Comment by theodorDiaconu** [comment] 2017-01-26 07:50
This issue has been addressed and will be fixed in 1.1.7

**Closed** 2017-01-26 07:52 UTC
Labels: need-more-info
