### ISSUE TITLE
[Exception] Removed nonexistent document

### ISSUE THREAD

**Issue by clayne11** [cult-of-coders/redis-oplog#145] opened 2017-04-03 17:13 UTC
```
[server-internal] Exception in queued task: Error: Removed nonexistent document 5324TvAxi9MTLsSFS at [object Object]._.extend.removed (packages/ddp-server/livedata_server.js:202:17) at [object Object]._.extend.
```

**Comment by evolross** [comment] 2017-04-03 17:23
FWIW, I get this same exception too (and many others), but I haven't started using `redis-oplog` yet.  From my research it has something to do with one of the following:

1. Multiple subscriptions publishing the same document(s). Then when one is removed, the first publication's `this.removed` fires, then the other publication throws this error because when its `this.removed` callback fires, the document is already removed. Google around for this, there's some discussions about it.

2. Using the `collection-hooks` package and having a hook fire on a document that's been removed

**Comment by ramezrafla** [comment] 2017-04-06 20:09
It likely relates to `mongo/extendObserveChanges` with reactive publications where `removed` gets called multiple times. I tried adding a `try / catch` around the offending section and that messes up the subscription (data disappears from livedata). So it does seem like we need to break the call.

Somewhere in redis-oplog reactive publications call the change handlers more than once. Maybe we need somewhere a check to break this cycle. The same happens with changed, it can get called often.

**Comment by theodorDiaconu** [comment] 2017-04-10 13:14
@clayne11 I need to reproduce this and I will find a fix. I believe it can be easily solved by interogating the user's collectionView and check for those docs before calling remove, but then I ask myself, shouldn't this be default meteor behavior, why did they choose not to do it ?

**Comment by evolross** [comment] 2017-04-10 18:16
Here's the Meteor issue, which they closed, hence it not being addressed.  I guess this previously would actually crash your Meteor server, so they just added exception handling and closed it.

[https://github.com/meteor/meteor/issues/944](url)

**Comment by theodorDiaconu** [comment] 2017-04-13 13:47
@clayne11 @evolross @ramezrafla 
As glasser said:
"That's as designed. Each subscription represents a set of documents. If you want two separate sets that are merged together, use two separate subscriptions."

This error can happen with reactive-publish or publishComposite like this:
posts Many2Many tags

So basically for each post, you create a live-query for tags, so:
```
// lets assume a **tag X** in both post1 and post2
post1: return Tags.find({_id: post1.tagIds}); // observer1
post2: return Tags.find({_id: post2.tagIds}); // observer2
```

Now if **tag X** gets removed in the backend, it will hit both observers, first one will remove it from it's data-store then send it to the ddp, the second one will remove it from it's data-store and send it to the ddp (-> exception occurs)

How to solve this ? Try to separate publications, there really is no other way.

**Comment by theodorDiaconu** [comment] 2017-04-13 14:38
@clayne11 indeed Meteor doesn't, but you could get around that limitation and it can result into that exception.

So your publication is a return of a collection with some ids. Can you reproduce this error ? If yes, how does it happen, you already gave a valuable clue, because when we search by _id's we go into the "Direct Processing" strategy. 

Now tell me how you reproduce it and I will solve it asap, cheers

**Comment by ramezrafla** [comment] 2017-04-25 06:32
Thanks @theodorDiaconu and sorry for delay.
I'll try to get you a repo to reproduce this. The thing is, it can get tricky as it is not 100% repeatable.

**Comment by theodorDiaconu** [comment] 2017-11-03 08:36
@clayne11  @evolross 
I think it was related to server autorun. Did you have that in your apps ?

**Comment by theodorDiaconu** [comment] 2017-11-06 13:53
This can happen in the following scenario:
- Given two publications that share the same document
- We remove that document from database
- "removed" will be called twice.

Maybe find a way to execute removes at the end of processing each observable collection.

**Comment by theodorDiaconu** [comment] 2017-11-06 14:01
Created new issue around this.

**Closed by theodorDiaconu** 2017-11-06 14:01 UTC
Labels: THINK!
