### ISSUE TITLE
Strange issue when a field (roles: 1) is included in the publication

### ISSUE THREAD

**Issue by ixdi** [cult-of-coders/redis-oplog#187] opened 2017-11-02 20:25 UTC
Hi,

We tested version 1.2.2 and publications are never get ready. Loading state runs forever. 

Can we connect to the same redis database from two applications (test and production)? We are doing so and it runs normally with 1.2.1_1 

After 1.2.2 we have loaded version 1.2.1_1 again and it runs normally.

Thanks

**Comment by ramezrafla** [comment] 2017-11-02 20:52
We do get issues too with 1.2.2 -- keeps disconnecting.

**Comment by ramezrafla** [comment] 2017-11-02 21:01
Confirming that reverting to 1.2.1_1 fixes (commit 86e44a25bef4577a3f1c5292708872a137145a2e titled 'Bump to 1.2.1_1') but the commit right after (95f43691eef8ca02a749e0be652cd56e24ece196) breaks it

**Comment by theodorDiaconu** [comment] 2017-11-02 22:00
Any errors on the server-side ? This is very strange, all tests are passing.

**Comment by theodorDiaconu** [comment] 2017-11-02 22:09
@ixdi @ramezrafla I'm working on it at the moment.

**Comment by theodorDiaconu** [comment] 2017-11-02 22:43
@ixdi I can't seem to reproduce this :( so help me understand, does it work locally for you ok ?

**Comment by ixdi** [comment] 2017-11-03 08:52
@theodorDiaconu we updated to 1.2.2_1 but the result is the same. Locally does not work either. It fails when user sign in.

We paste an extract of locally debugged logs, that were repeated until we stopped the meteor server. We are using redis version 3.2.11

```js
I20171103-09:35:08.870(1)? [1509698108870] - [PublicationFactory] Created new subscribers for redis for: meteor_accounts_loginServiceConfiguration::{}{"fields":{"secret":0}}
I20171103-09:35:08.870(1)? [1509698108870] - [PublicationEntry] Performing initial add for observer
I20171103-09:35:08.871(1)? [1509698108871] - [RedisSubscriptionManager] Subscribing to channel: meteor_accounts_loginServiceConfiguration
I20171103-09:35:08.872(1)? [1509698108872] - [PublicationEntry] Completed initial add for observer
I20171103-09:35:08.876(1)? [1509698108876] - [Main] New incomming subscription for publication: userData
I20171103-09:35:08.876(1)? [1509698108876] - [Main] New incomming subscription for publication: usersAssoc
I20171103-09:35:08.877(1)? [1509698108877] - [Main] New incomming subscription for publication: getConfs
I20171103-09:35:51.069(1)? [1509698151069] - [PublicationEntry] No other observers for: meteor_accounts_loginServiceConfiguration::{}{"fields":{"secret":0}}. Stopping subscription to redis.
I20171103-09:35:51.070(1)? [1509698151070] - [RedisSubscriptionManager] Unsubscribing from channel: meteor_accounts_loginServiceConfiguration
I20171103-09:35:51.821(1)? [1509698151820] - [PublicationFactory] Created new subscribers for redis for: meteor_accounts_loginServiceConfiguration::{}{"fields":{"secret":0}}
I20171103-09:35:51.821(1)? [1509698151820] - [PublicationEntry] Performing initial add for observer
I20171103-09:35:51.822(1)? [1509698151822] - [RedisSubscriptionManager] Subscribing to channel: meteor_accounts_loginServiceConfiguration
I20171103-09:35:51.824(1)? [1509698151824] - [PublicationEntry] Completed initial add for observer
I20171103-09:35:51.828(1)? [1509698151828] - [Main] New incomming subscription for publication: getConfs
I20171103-09:36:11.424(1)? [1509698171424] - [PublicationEntry] No other observers for: meteor_accounts_loginServiceConfiguration::{}{"fields":{"secret":0}}. Stopping subscription to redis.
I20171103-09:36:11.424(1)? [1509698171424] - [PublicationFactory] Created new subscribers for redis for: meteor_accounts_loginServiceConfiguration::{}{"fields":{"secret":0}}
I20171103-09:36:11.424(1)? [1509698171424] - [PublicationEntry] Performing initial add for observer
I20171103-09:36:11.426(1)? [1509698171426] - [PublicationFactory] Created new subscribers for redis for: users::{"_id":"eKoJEXFTHFdKwYhDx","services.resume.loginTokens.hashedToken":"DBpGGcWqBWkawEDU6+6dhlHiHGSeZfAz7bSFR4wDtVg="}{"fields":{"_id":1}}
I20171103-09:36:11.427(1)? [1509698171426] - [PublicationEntry] Performing initial add for observer
I20171103-09:36:11.427(1)? [1509698171427] - [RedisSubscriptionManager] Unsubscribing from channel: meteor_accounts_loginServiceConfiguration
I20171103-09:36:11.428(1)? [1509698171428] - [PublicationEntry] Completed initial add for observer
I20171103-09:36:11.430(1)? [1509698171429] - [RedisSubscriptionManager] Subscribing to channel: meteor_accounts_loginServiceConfiguration
I20171103-09:36:11.430(1)? [1509698171430] - [RedisSubscriptionManager] Subscribing to channel: users::eKoJEXFTHFdKwYhDx
I20171103-09:36:11.431(1)? [1509698171431] - [PublicationEntry] Completed initial add for observer
I20171103-09:36:11.431(1)? [1509698171431] - [Main] New incomming subscription for publication: getConfs
I20171103-09:36:11.434(1)? [1509698171434] - [PublicationFactory] Created new subscribers for redis for: users::{"_id":"eKoJEXFTHFdKwYhDx"}{"fields":{"profile":1,"username":1,"emails":1}}
I20171103-09:36:11.434(1)? [1509698171434] - [PublicationEntry] Performing initial add for observer
I20171103-09:36:11.435(1)? [1509698171435] - [PublicationEntry] Completed initial add for observer
I20171103-09:36:11.440(1)? [1509698171440] - [Main] New incomming subscription for publication: userData
I20171103-09:36:11.441(1)? [1509698171441] - [PublicationFactory] Created new subscribers for redis for: users::{"_id":"eKoJEXFTHFdKwYhDx"}{"limit":1,"fields":{"username":1,"emails.address":1,"profile":1,"parent":1},"sort":{"createdAt":1}}
I20171103-09:36:11.442(1)? [1509698171441] - [PublicationEntry] Performing initial add for observer
I20171103-09:36:11.443(1)? [1509698171443] - [RedisSubscriptionManager] Subscribing to channel: users
I20171103-09:36:11.444(1)? [1509698171444] - [PublicationEntry] Completed initial add for observer
I20171103-09:36:11.444(1)? [1509698171444] - [Main] New incomming subscription for publication: usersAssoc
I20171103-09:36:11.448(1)? [1509698171448] - [PublicationFactory] Created new subscribers for redis for: users::{"_id":{"$in":["c76nFngLhej8PcCdT","J6pyThq7Sa5xTEj5h","78SyjAh7vQcbXpPgP"]}}{"fields":{"profile":1,"username":1},"sort":{"createdAt":1}}
I20171103-09:36:11.449(1)? [1509698171448] - [PublicationEntry] Performing initial add for observer
I20171103-09:36:11.449(1)? [1509698171449] - [RedisSubscriptionManager] Subscribing to channel: users::c76nFngLhej8PcCdT
I20171103-09:36:11.451(1)? [1509698171451] - [RedisSubscriptionManager] Subscribing to channel: users::J6pyThq7Sa5xTEj5h
I20171103-09:36:11.451(1)? [1509698171451] - [RedisSubscriptionManager] Subscribing to channel: users::78SyjAh7vQcbXpPgP
I20171103-09:36:11.453(1)? [1509698171452] - [PublicationEntry] Completed initial add for observer
I20171103-09:36:11.591(1)? [1509698171591] - [Main] New incomming subscription for publication: getConfs
I20171103-09:36:11.985(1)? [1509698171983] - [PublicationEntry] No other observers for: users::{"_id":"eKoJEXFTHFdKwYhDx","services.resume.loginTokens.hashedToken":"DBpGGcWqBWkawEDU6+6dhlHiHGSeZfAz7bSFR4wDtVg="}{"fields":{"_id":1}}. Stopping subscription to redis.
I20171103-09:36:11.985(1)? [1509698171983] - [PublicationEntry] No other observers for: meteor_accounts_loginServiceConfiguration::{}{"fields":{"secret":0}}. Stopping subscription to redis.
I20171103-09:36:11.985(1)? [1509698171984] - [PublicationFactory] Created new subscribers for redis for: users::{"_id":"eKoJEXFTHFdKwYhDx","services.resume.loginTokens.hashedToken":"ApaEAwfKIuFxGWtj8tLFmW90ZYoBc83vKK3R0fVET50="}{"fields":{"_id":1}}
I20171103-09:36:11.986(1)? [1509698171984] - [PublicationEntry] Performing initial add for observer
I20171103-09:36:11.986(1)? [1509698171984] - [Main] Stopping the Meteor subscription for publication: userData
I20171103-09:36:11.986(1)? [1509698171984] - [PublicationEntry] No other observers for: users::{"_id":"eKoJEXFTHFdKwYhDx"}{"limit":1,"fields":{"username":1,"emails.address":1,"profile":1,"parent":1},"sort":{"createdAt":1}}. Stopping subscription to redis.
I20171103-09:36:11.986(1)? [1509698171985] - [RedisSubscriptionManager] Unsubscribing from channel: meteor_accounts_loginServiceConfiguration
I20171103-09:36:11.987(1)? [1509698171985] - [Main] Stopping the Meteor subscription for publication: usersAssoc
I20171103-09:36:11.987(1)? [1509698171985] - [PublicationEntry] No other observers for: users::{"_id":{"$in":["c76nFngLhej8PcCdT","J6pyThq7Sa5xTEj5h","78SyjAh7vQcbXpPgP"]}}{"fields":{"profile":1,"username":1},"sort":{"createdAt":1}}. Stopping subscription to redis.
I20171103-09:36:11.987(1)? [1509698171985] - [PublicationEntry] No other observers for: users::{"_id":"eKoJEXFTHFdKwYhDx"}{"fields":{"profile":1,"username":1,"emails":1}}. Stopping subscription to redis.
I20171103-09:36:11.987(1)? [1509698171985] - [PublicationFactory] Created new subscribers for redis for: meteor_accounts_loginServiceConfiguration::{}{"fields":{"secret":0}}
```

**Comment by theodorDiaconu** [comment] 2017-11-03 08:54
@ixdi I'm not seeing any real error, so what you are stating is the fact that the subscription in client-side never gets ready ? Is the data pushed ? Can you inspect the websockets a bit ?

**Comment by ixdi** [comment] 2017-11-03 08:55
Ok we found the problem! 

It ocurrs when there's a publication of type:
```js
Meteor.publish('pubData', function() {
   const cur = Collection.find({ ... });
   cur.forEach(doc => this.added('collectionName', doc._id, doc));
   this.ready();
});
```

**Comment by theodorDiaconu** [comment] 2017-11-03 08:58
@ixdi the behaviour of redis publication is that, if it doesn't return anything it delegates it to the old Meteor.publish... I will try to write a test for this, see if I can break it. So the problem is that the pubData never becomes 'ready' ?

**Comment by ixdi** [comment] 2017-11-03 09:00
@theodorDiaconu yes, we think this is.

When we change that publication to this, there's no problem

```js
Meteor.publish('pubData', function() {
   return Collection.find({ ... });
})
```

**Comment by theodorDiaconu** [comment] 2017-11-03 10:00
@ixdi wrote a test for it, and it passed. This is so super strange. As I mentioned above if you do it like that, it should work out of the box. Are you absolutely sure that's the cause ?

**Comment by theodorDiaconu** [comment] 2017-11-03 10:05
@ixdi can you move on the release/1.2.3 branch to check it ?

cd packages ; git clone ... ; git checkout release/1.2.3

**Comment by theodorDiaconu** [comment] 2017-11-03 10:06
Texts are here: https://github.com/cult-of-coders/redis-oplog/tree/release/1.2.3/testing/custom-publications

**Comment by ixdi** [comment] 2017-11-03 12:01
It's really strange. 

Version 1.2.3 always fail, although we use the code that does not fail with 1.2.2_1

```js
Meteor.publish('pubData', function() {
   return Collection.find({ ... });
})
```

**Comment by theodorDiaconu** [comment] 2017-11-03 13:42
@ixdi so you are saying it fails with 1.2.3 on that simple publication ?

**Comment by theodorDiaconu** [comment] 2017-11-03 13:43
Above you were saying that it fails for 1.2.2

**Comment by ixdi** [comment] 2017-11-06 11:04
Hi @theodorDiaconu,

We don't know why but we discovered that it fails when we subscribe to a user publication that sends user roles. If we do not send the roles field then it does not fail.

We send roles field with other extra user fields when signin in because, as you know, Meteor only sends username, email and profile. We disabled publishing roles in the alanning:roles package.

Roles field is of the type,
```js
"roles" : {
    "__global_roles__" : [
        "coach"
    ], 
    "PLAN" : [
        "team"
    ], 
    "c76nFngLhej8PcCdT" : [
        "subscribed", 
        "coach-associated"
    ], 
    "J6pyThq7Sa5xTEj5h" : [
        "subscribed", 
        "coach-associated"
    ], 
    "78SyjAh7vQcbXpPgP" : [
        "subscribed", 
        "coach-associated"
    ]
}
```

Publication is

```js
Meteor.publish('userData', function() {
  // check logged in
  if (!this.userId) {
    return this.ready();
  }
  const uid = this.userId;
  return Meteor.users.find({
    _id: uid,
  }, {
    limit: 1,
    fields: {
      username: 1,
      'emails.address': 1,
      profile: 1,
      subscription: 1,
      license: 1,
      roles: 1,  // when removing this field it works
    },
    sort: {
      createdAt: 1,
    },
  });
});
```

**Comment by theodorDiaconu** [comment] 2017-11-06 13:48
@ixdi another question would be about load order, do you have redis-oplog as your top package?

**Comment by ixdi** [comment] 2017-11-06 15:32
@theodorDiaconu Yes, it's the first one in the packages.

Fail means that is subscribing and unsubscribing all the time when a user sign in. The ready state is set correctly because screen loads but some components start blinking. If user is not logged in there's no such error. 

When the roles field is present the redis-oplog logs show this two lines and then start to repeat subription and unsubscription messages all the time. When the roles field is not present logs finish before this two lines when user sign in.

```js
[PublicationEntry] No other observers for: users::{"_id":"eKoJEXFTHFdKwYhDx","services.resume.loginTokens.hashedToken":"z5I5QMgVdozlNloaRCdfm303TeE+vGyIG88HHfJeEDI="}{"fields":{"_id":1}}. Stopping subscription to redis.
[PublicationEntry] No other observers for: meteor_accounts_loginServiceConfiguration::{}{"fields":{"secret":0}}. Stopping subscription to redis.
```
Maybe it's a problem with our code but 1.2.1 version works well with roles field. It fail as of version 1.2.2 (included).

**Comment by theodorDiaconu** [comment] 2017-11-06 16:49
@ixdi I think it's because in 1.2.2 I removed the reactivity for collections that don't have a `_cursorDescription` inside them. I knew it was there for a reason, but because there wasn't any test to break I removed it. I need to investigate to properly solve this.

**Comment by theodorDiaconu** [comment] 2017-11-07 11:17
This is one of the strangest issues @ixdi 
https://github.com/cult-of-coders/redis-oplog/blob/feature/redis-vent/testing/accounts/client.js

I wrote a test, I had my debug one, there's no unsubscribing unless I do Meteor.logout()
Can you test with "feature/redis-vent" branch ? This bug is bugging me seriously.

@ixdi If not, would it be possible for you to create a reproduction repo?
Some questions:
- What packages are you using ?
- Can you show me "usersAssoc" and "getConfs" subscription?

@ramezrafla can you also test please ?

**Comment by theodorDiaconu** [comment] 2017-11-07 17:06
@ixdi does this also happen with feature/redis-vent branch ? Can you please try ? This issue is so strange.

**Comment by ixdi** [comment] 2017-11-07 17:11
Yes, sorry I didn't mention. It fails with redis-vent.

**Comment by theodorDiaconu** [comment] 2017-11-07 17:28
@ixdi clearly this is what you and Ramez have in common, I see that @ramezrafla is a contributor here: https://github.com/ccorcos/meteor-subs-cache/blob/master/src/SubsCache.js

For sure he's using it also.

**Comment by theodorDiaconu** [comment] 2017-11-07 17:43
@ixdi I need to see if the client sends the "unsubscribe" event, can you inspect the websocket frames and dump them to me ? Also in your RedisOplog debug log, I didn't see any {"roles":1} as field.

As of know is that still the case ? If you comment out roles field it works ?

**Comment by theodorDiaconu** [comment] 2017-11-09 06:20
This will be fixed I realised what my issue was :)

**Comment by ixdi** [comment] 2017-11-09 09:21
Uou, thanks @theodorDiaconu !!

We removed subs-cache and did other actions but nothing worked.

**Comment by theodorDiaconu** [comment] 2017-11-09 10:33
@ixdi yeah it was very strange issue, by any chance do you have user-presence ?

**Comment by ixdi** [comment] 2017-11-09 11:21
No, we don't use this package.

**Comment by theodorDiaconu** [comment] 2017-11-09 11:22
@ixdi ok no problem I found the bug, and I'm going to fix it.

**Comment by theodorDiaconu** [comment] 2017-11-09 11:24
@ixdi check now the redis-vent branch. it should work. I'm now working on making Redis Oplog even more performant, then launching 1.2.4

**Comment by ixdi** [comment] 2017-11-09 12:00
Ok now! Thanks!!

**Closed** 2017-11-09 12:18 UTC
Labels: need-more-info
