### ISSUE TITLE
Vent subscription: Possible to reuse?

### ISSUE THREAD

**Issue by dnish** [cult-of-coders/redis-oplog#251] opened 2018-03-12 19:45 UTC
Hey,
due to performance reasons, I try to "reuse" a subscription to minimize the CPU usage. When I do

    Vent.subscribe('rtcMessages', {chatId: this.currentChatId});

I get the following subscription params within the logs:

```
params: ["gtpKnDxDZKGJb6suT",{chatId:"vQCaa22hBE3xW9gwR"}]
```

I'm just wondering about gtpKnDxDZKGJb6suT? Is this a random id? So If I understand it right, both clients within the chat would generate a new subscription instead of using the same (because both use different params)?

// Edit:

https://github.com/cult-of-coders/redis-oplog/blob/0bb6ea4e214bb148d203adbfe56cfba8c2d6e676/lib/vent/VentClient.js#L76

I guess this line causes the issue. <code>this._id</code> gets a value from <code>Random.id()</code>.

We've some server performance issues since using the subscription. Currently each user generates a new subscription for himself:

    Vent.subscribe('rtcMessages', {userId: Meteor.userId()});

If 300 users are online, we'll have 300 active subscriptions. If we could generate a subscription for every active chat, we would be able to reduce this number to 150 active subscriptions.

**Comment by dnish** [comment] 2018-03-12 21:48
@theodorDiaconu Maybe we can hash the parameters (https://www.npmjs.com/package/object-hash) and use the generated hash as id?

**Comment by theodorDiaconu** [comment] 2018-03-13 16:20
@dnish the reason for having unique _id is because we have to identify what local storage to update so you can subscribe with vent to the same publication multiple times, basically the idea of Vent is re-usable by nature because it is managed by PubSubManager, different data will be sent to different clients, the impact is minimal I believe, maybe we can minimize the bandwidth by finding a increasing id that gets generated on the client.

**Comment by theodorDiaconu** [comment] 2018-03-20 15:20
@dnish I now understand better what you want. The problem is that if you use userId inside event, you can no longer rely on the usage of the same handler for it. I'll think about it, it should be possible.

**Comment by dnish** [comment] 2018-03-20 15:56
@theodorDiaconu Yeah, but I was also thinking about some issues. If I got it right, this "reusing" is only available per instance. A Meteor app which needs redis-oplog has normally multiple instances running. So if 2 users are not connected to the same instance, we'll still get 2 subscriptions instead of one. So I don't know if this feature is really needed. It may depend of the use case.

**Comment by theodorDiaconu** [comment] 2018-03-28 14:37
I'm going to close this, Vent will remain as simple as possible, any other abstraction / caching / stuff can be done outside of it.

**Closed by theodorDiaconu** 2018-03-28 14:37 UTC
Labels: THINK!
